//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizResultServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultModel", Namespace="http://schemas.datacontract.org/2004/07/APISERVICESOAP.SoapModels")]
    public partial class QuizResultModel : object
    {
        
        private System.Nullable<long> AttemptTimeField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private string CreatedByField;
        
        private System.Nullable<bool> DoHaveFeedbackField;
        
        private string FeedBackField;
        
        private long IdField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Nullable<bool> IsDeletedField;
        
        private System.Nullable<System.DateTime> ModifiedAtField;
        
        private string ModifiedByField;
        
        private long QuizIdField;
        
        private string QuizResultCodeField;
        
        private string RecommendedAnswerDataField;
        
        private long ScoreField;
        
        private string SuggestionContentField;
        
        private double TimeCompletedField;
        
        private string UserAnswerDataField;
        
        private long UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AttemptTime
        {
            get
            {
                return this.AttemptTimeField;
            }
            set
            {
                this.AttemptTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this.CreatedByField;
            }
            set
            {
                this.CreatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DoHaveFeedback
        {
            get
            {
                return this.DoHaveFeedbackField;
            }
            set
            {
                this.DoHaveFeedbackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedBack
        {
            get
            {
                return this.FeedBackField;
            }
            set
            {
                this.FeedBackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDeleted
        {
            get
            {
                return this.IsDeletedField;
            }
            set
            {
                this.IsDeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedAt
        {
            get
            {
                return this.ModifiedAtField;
            }
            set
            {
                this.ModifiedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModifiedBy
        {
            get
            {
                return this.ModifiedByField;
            }
            set
            {
                this.ModifiedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuizId
        {
            get
            {
                return this.QuizIdField;
            }
            set
            {
                this.QuizIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuizResultCode
        {
            get
            {
                return this.QuizResultCodeField;
            }
            set
            {
                this.QuizResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecommendedAnswerData
        {
            get
            {
                return this.RecommendedAnswerDataField;
            }
            set
            {
                this.RecommendedAnswerDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuggestionContent
        {
            get
            {
                return this.SuggestionContentField;
            }
            set
            {
                this.SuggestionContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TimeCompleted
        {
            get
            {
                return this.TimeCompletedField;
            }
            set
            {
                this.TimeCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAnswerData
        {
            get
            {
                return this.UserAnswerDataField;
            }
            set
            {
                this.UserAnswerDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuizResultCreateModel", Namespace="http://schemas.datacontract.org/2004/07/APISERVICESOAP.SoapModels")]
    public partial class QuizResultCreateModel : object
    {
        
        private System.Nullable<long> AttemptTimeField;
        
        private System.Nullable<bool> DoHaveFeedbackField;
        
        private string FeedBackField;
        
        private long QuizIdField;
        
        private string QuizResultCodeField;
        
        private string RecommendedAnswerDataField;
        
        private long ScoreField;
        
        private string SuggestionContentField;
        
        private double TimeCompletedField;
        
        private string UserAnswerDataField;
        
        private long UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> AttemptTime
        {
            get
            {
                return this.AttemptTimeField;
            }
            set
            {
                this.AttemptTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DoHaveFeedback
        {
            get
            {
                return this.DoHaveFeedbackField;
            }
            set
            {
                this.DoHaveFeedbackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedBack
        {
            get
            {
                return this.FeedBackField;
            }
            set
            {
                this.FeedBackField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QuizId
        {
            get
            {
                return this.QuizIdField;
            }
            set
            {
                this.QuizIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuizResultCode
        {
            get
            {
                return this.QuizResultCodeField;
            }
            set
            {
                this.QuizResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecommendedAnswerData
        {
            get
            {
                return this.RecommendedAnswerDataField;
            }
            set
            {
                this.RecommendedAnswerDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuggestionContent
        {
            get
            {
                return this.SuggestionContentField;
            }
            set
            {
                this.SuggestionContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TimeCompleted
        {
            get
            {
                return this.TimeCompletedField;
            }
            set
            {
                this.TimeCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAnswerData
        {
            get
            {
                return this.UserAnswerDataField;
            }
            set
            {
                this.UserAnswerDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuizResultServiceReference.IQuizResultSoapService")]
    public interface IQuizResultSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/GetAll", ReplyAction="http://tempuri.org/IQuizResultSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/GetById", ReplyAction="http://tempuri.org/IQuizResultSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel> GetByIdAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/Create", ReplyAction="http://tempuri.org/IQuizResultSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(QuizResultServiceReference.QuizResultCreateModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/Update", ReplyAction="http://tempuri.org/IQuizResultSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(QuizResultServiceReference.QuizResultModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/Delete", ReplyAction="http://tempuri.org/IQuizResultSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/Search", ReplyAction="http://tempuri.org/IQuizResultSoapService/SearchResponse")]
        System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel[]> SearchAsync(string qzcode, string sugContent, string feedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuizResultSoapService/GetChatBotResponse", ReplyAction="http://tempuri.org/IQuizResultSoapService/GetChatBotResponseResponse")]
        System.Threading.Tasks.Task<string> GetChatBotResponseAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IQuizResultSoapServiceChannel : QuizResultServiceReference.IQuizResultSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class QuizResultSoapServiceClient : System.ServiceModel.ClientBase<QuizResultServiceReference.IQuizResultSoapService>, QuizResultServiceReference.IQuizResultSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public QuizResultSoapServiceClient() : 
                base(QuizResultSoapServiceClient.GetDefaultBinding(), QuizResultSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IQuizResultSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(QuizResultSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), QuizResultSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(QuizResultSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(QuizResultSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public QuizResultSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel> GetByIdAsync(long id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(QuizResultServiceReference.QuizResultCreateModel request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(QuizResultServiceReference.QuizResultModel request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(long id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public System.Threading.Tasks.Task<QuizResultServiceReference.QuizResultModel[]> SearchAsync(string qzcode, string sugContent, string feedback)
        {
            return base.Channel.SearchAsync(qzcode, sugContent, feedback);
        }
        
        public System.Threading.Tasks.Task<string> GetChatBotResponseAsync(string message)
        {
            return base.Channel.GetChatBotResponseAsync(message);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuizResultSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IQuizResultSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7139/PremaritalCounselingSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return QuizResultSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IQuizResultSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return QuizResultSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IQuizResultSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IQuizResultSoapService,
        }
    }
}
