// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Micro1.BusinessObject.Shared.Models;

public partial class QuizResult 
{
    [Key]
    public long Id { get; set; }

    public long Score { get; set; }

    public long QuizId { get; set; }

    public long UserId { get; set; }

    public string? QuizResultCode { get; set; } = "RESULT-" + Guid.NewGuid().ToString();

    public double TimeCompleted { get; set; }

    public long? AttemptTime { get; set; } = 1;
    public bool? DoHaveFeedback { get; set; } = false;
    public string? FeedBack { get; set; } // Expert or Admin can take time to give the feedback

    //Suggestion properties - AI Generated Only (can be updated no limit times)
    public string? SuggestionContent { get; set; } = "Unavailable yet";


    #region adding later version of this entity
    public string UserAnswerData { get; set; }// large text data
    public string RecommendedAnswerData { get; set; }// large text data

    #endregion

    public virtual User User { get; set; }
}