// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace BusinessObject.Shared.Models;

public partial class Quiz 
{
    public long Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string? Image { get; set; }

    public long? Duration { get; set; }

    public string? DurationUnit { get; set; } = "seconds";

    public double? AvgTimeCompleted { get; set; }
    //Regex here when save and read from database eg. "tag1, tag2, tag3"
    public string? Tags { get; set; }

    public string? Difficulty { get; set; } = "Undefined";

    public long? PassScore { get; set; }

    public virtual ICollection<QuizResult> QuizResults { get; set; } = new List<QuizResult>();
}